import webbrowser                                                                                  2                                                                                                    3 url = "https://minosis.com"  # Reemplaza con la URL
webbrowser.open(url)
print("https://minosis.com")
print("https://www.indec.gob.ar")
print("https://www.afip.gob.ar")
print("https://www.bcra.gob.ar")
print("https://www.economia.gob.ar")
print("https://www.trabajo.gob.ar")
print("https://www.argentina.gob.ar/salud")
print("https://www.argentina.gob.ar/superintendencia-de-seguros-de-la-nacion")
print("https://www.cammesa.com")
print("http://www.uca.edu.ar")
print("https://www.dpn.gob.ar")
